import type { Metadata } from "next";
import "./globals.css";
import '@mantine/core/styles.css';
import "@mantine/charts/styles.css";
import Providers from "@/components/Providers";
import '@mantine/notifications/styles.css';


export const metadata: Metadata = {
  // title: "Create Next App",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {children}
          </Providers>
      </body>
    </html>
  );
}
